[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "prodict"
version = "0.1.0"
description = "ProDICT pipeline module. Use it to run on the terminal"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]

[tool.flake8]
max-line-length = 160